# Generated by Django 3.0.4 on 2021-07-05 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_project', models.CharField(max_length=50)),
                ('posting_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 12, 30, 52, 7776))),
            ],
        ),
    ]
