# Generated by Django 3.0.4 on 2021-07-05 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentportalapp', '0005_auto_20210705_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_project_title',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 20, 55, 0, 670591)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 5, 20, 55, 0, 670591)),
        ),
    ]
