# Generated by Django 3.0.4 on 2021-07-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentportalapp', '0006_auto_20210705_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial Paid', 'Partially Paid')], default='Unpaid', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 10, 59, 17, 418062)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 6, 10, 59, 17, 418062)),
        ),
    ]
